package com.aulenor.ottormastar.data

import android.content.Context
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

// Mirrors shared/plants.json, generated by scripts/export-native-data.cjs.
// Regenerate after any edit to src/data/* — never hand-edit the JSON.

enum class Language(val code: String, val label: String, val shortLabel: String) {
    SAH("sah", "Саха", "Саха"),
    RU("ru", "Русский", "Рус"),
    EN("en", "English", "Eng");

    companion object {
        fun from(code: String): Language = entries.firstOrNull { it.code == code } ?: SAH
    }
}

@Serializable
data class LocalizedText(val sah: String, val ru: String, val en: String) {
    operator fun get(lang: Language): String = when (lang) {
        Language.SAH -> sah
        Language.RU -> ru
        Language.EN -> en
    }
}

@Serializable
data class PlantNames(val sah: String, val ru: String, val en: String, val latin: String) {
    operator fun get(lang: Language): String = when (lang) {
        Language.SAH -> sah
        Language.RU -> ru
        Language.EN -> en
    }
}

@Serializable
data class Plant(
    val id: String,
    val slug: String,
    val imageId: String,
    val hasIllustration: Boolean,
    val names: PlantNames,
    val description: LocalizedText,
    val medicinalUses: LocalizedText,
    val habitat: LocalizedText,
    val bloomingSeason: String,
    val categories: List<String>,
    val color: String,
) {
    /**
     * "Further reading": language-matched Wikipedia lookup, same query
     * strategy as the web (sah name for sah wiki, Latin binomial elsewhere).
     */
    fun wikipediaUrl(lang: Language): String {
        val query = if (lang == Language.SAH) {
            names.sah.replace(Regex("""\s*\([^)]*\)\s*"""), " ").trim()
        } else {
            names.latin
        }
        return "https://${lang.code}.wikipedia.org/wiki/Special:Search?search=" +
            java.net.URLEncoder.encode(query, "UTF-8")
    }
}

/**
 * Blooming-season sort, same order table as the web catalog:
 * earliest start first, unknown seasons last.
 */
object SeasonOrder {
    private val order = listOf(
        "spring", "may-june", "may-july", "june-july",
        "june-august", "summer", "july-august", "autumn",
    )

    fun rank(season: String): Int = order.indexOf(season).let { if (it == -1) order.size else it }
}

/** Two-digit index numeral like the web's plate numbers: 0 → "01". */
fun plateNumeral(index: Int): String = "%02d".format(index + 1)

@Serializable
data class Country(val id: String, val imageBase: String, val plants: List<Plant>)

@Serializable
data class PlantData(
    val version: Int,
    val imageHost: String,
    val defaultCountry: String,
    val countries: List<Country>,
)

/**
 * Bundled dataset, loaded once from assets. The JSON ships in the APK, so a
 * decode failure is a build error, not a runtime condition — crash loudly.
 */
object PlantStore {
    lateinit var data: PlantData
        private set

    fun load(context: Context) {
        if (::data.isInitialized) return
        val raw = context.assets.open("plants.json").bufferedReader().use { it.readText() }
        data = Json { ignoreUnknownKeys = true }.decodeFromString(raw)
    }

    fun country(id: String): Country =
        data.countries.firstOrNull { it.id == id }
            ?: data.countries.first { it.id == data.defaultCountry }

    val availableCountries: List<Country>
        get() = data.countries.filter { it.plants.isNotEmpty() }

    fun findPlant(slug: String): Pair<Plant, Country>? {
        for (country in data.countries) {
            country.plants.firstOrNull { it.slug == slug }?.let { return it to country }
        }
        return null
    }
}
