package com.aulenor.ottormastar.data

import android.content.Context
import android.os.Build
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.io.File
import java.net.HttpURLConnection
import java.net.URL

// Mirrors shared/plants.json, generated by scripts/export-native-data.cjs.
// Regenerate after any edit to src/data/* — never hand-edit the JSON.

enum class Language(val code: String, val label: String, val shortLabel: String) {
    // sah/ru/en are the trilingual base; mn/zh are added for the Mongolia
    // collection. Which subset a reader sees is decided per country.
    SAH("sah", "Саха", "Саха"),
    RU("ru", "Русский", "Рус"),
    EN("en", "English", "Eng"),
    MN("mn", "Монгол", "Мон"),
    ZH("zh", "中文", "中");

    companion object {
        fun from(code: String): Language = entries.firstOrNull { it.code == code } ?: SAH
    }
}

@Serializable
data class LocalizedText(
    val sah: String,
    val ru: String,
    val en: String,
    val mn: String? = null,
    val zh: String? = null,
) {
    // Requested language, or English as the universal fallback (mn/zh are
    // absent on Yakutia plants and never queried there).
    operator fun get(lang: Language): String = when (lang) {
        Language.SAH -> sah
        Language.RU -> ru
        Language.EN -> en
        Language.MN -> mn ?: en
        Language.ZH -> zh ?: en
    }
}

@Serializable
data class PlantNames(
    val sah: String,
    val ru: String,
    val en: String,
    val latin: String,
    val mn: String? = null,
    val zh: String? = null,
) {
    operator fun get(lang: Language): String = when (lang) {
        Language.SAH -> sah
        Language.RU -> ru
        Language.EN -> en
        Language.MN -> mn ?: en
        Language.ZH -> zh ?: en
    }
}

@Serializable
data class Plant(
    val id: String,
    val slug: String,
    val imageId: String,
    val hasIllustration: Boolean,
    val names: PlantNames,
    val description: LocalizedText,
    val medicinalUses: LocalizedText,
    val habitat: LocalizedText,
    val bloomingSeason: String,
    val categories: List<String>,
    val color: String,
) {
    /**
     * "Further reading": language-matched Wikipedia lookup, same query
     * strategy as the web (sah name for sah wiki, Latin binomial elsewhere).
     */
    fun wikipediaUrl(lang: Language): String {
        // Always the reader's own Wikipedia subdomain. Native-language wikis
        // (Sakha/Mongolian/Chinese) resolve best from the plant's own name;
        // Russian/English from the Latin binomial.
        val query = if (lang == Language.SAH || lang == Language.MN || lang == Language.ZH) {
            names[lang].replace(Regex("""\s*\([^)]*\)\s*"""), " ").trim()
        } else {
            names.latin
        }
        return "https://${lang.code}.wikipedia.org/wiki/Special:Search?search=" +
            java.net.URLEncoder.encode(query, "UTF-8")
    }
}

/**
 * Blooming-season sort, same order table as the web catalog:
 * earliest start first, unknown seasons last.
 */
object SeasonOrder {
    private val order = listOf(
        "spring", "may-june", "may-july", "june-july",
        "june-august", "summer", "july-august", "autumn",
    )

    fun rank(season: String): Int = order.indexOf(season).let { if (it == -1) order.size else it }
}

/** Two-digit index numeral like the web's plate numbers: 0 → "01". */
fun plateNumeral(index: Int): String = "%02d".format(index + 1)

@Serializable
data class Country(
    val id: String,
    val imageBase: String,
    val plants: List<Plant>,
    /** Slug of the collection's cover plant (Sardaana for Yakutia, marigold for
     *  Mongolia) — the finest plate, not an arbitrary entry. */
    val heroSlug: String = "",
    /** Language codes this collection offers, in switcher order, plus its default. */
    val languages: List<String> = listOf("sah", "ru", "en"),
    val defaultLanguage: String = "sah",
) {
    /** Offered languages as enum values, resolving codes → Language. */
    val languageEnums: List<Language> get() = languages.map { Language.from(it) }
    val defaultLanguageEnum: Language get() = Language.from(defaultLanguage)

    /** The cover plant, resolved from [heroSlug]; falls back to the last entry
     *  so the hero is never null when the collection is non-empty. */
    val heroPlant: Plant? get() = plants.firstOrNull { it.slug == heroSlug } ?: plants.lastOrNull()
}

@Serializable
data class PlantData(
    val version: Int,
    val imageHost: String,
    val defaultCountry: String,
    val countries: List<Country>,
)

/**
 * The plant dataset, loaded ONCE at startup from the best available source: a
 * catalog previously cached from the website (by this same app build), else the
 * snapshot bundled in the APK. The bundle is the authoritative baseline so a
 * fresh, fully-offline first launch always works; the cache is an offline-first
 * overlay. New content published to the site is fetched in the background by
 * [refresh] and applied on the NEXT launch — the running session is never mutated.
 */
object PlantStore {
    /** Schema version this build understands. A hosted catalog with a different
     *  `version` is refused — an older app must never decode a newer shape. */
    private const val SCHEMA_VERSION = 1
    private const val PREFS = "catalog_cache"
    private const val KEY_APP_VERSION = "app_version"

    lateinit var data: PlantData
        private set

    private val json = Json { ignoreUnknownKeys = true }

    fun load(context: Context) {
        if (::data.isInitialized) return
        data = loadCachedCatalog(context) ?: loadBundled(context)
    }

    /** The snapshot compiled into the APK. A decode failure is a build error,
     *  not a runtime condition — crash loudly. */
    private fun loadBundled(context: Context): PlantData {
        val raw = context.assets.open("plants.json").bufferedReader().use { it.readText() }
        return json.decodeFromString(raw)
    }

    /** A previously-fetched catalog is trusted only if it was cached by THIS app
     *  build (so a new APK's fresh bundle always wins after an update) and its
     *  schema matches. Any miss/decode failure → null → fall back to bundled. */
    private fun loadCachedCatalog(context: Context): PlantData? = try {
        val prefs = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
        val cache = cacheFile(context)
        if (prefs.getLong(KEY_APP_VERSION, -1L) != appVersion(context) || !cache.exists()) {
            null
        } else {
            val decoded: PlantData = json.decodeFromString(cache.readText())
            decoded.takeIf { it.version == SCHEMA_VERSION }
        }
    } catch (_: Exception) {
        null
    }

    /** Best-effort over-the-air sync: fetch the hosted catalog and, if valid and
     *  schema-compatible, cache it for the next launch. Never touches the running
     *  session, never surfaces errors. Call once at app launch, after [load]. */
    fun refresh(context: Context) {
        if (!::data.isInitialized) return
        val host = data.imageHost
        CoroutineScope(Dispatchers.IO).launch {
            try {
                val conn = (URL("$host/catalog.json").openConnection() as HttpURLConnection).apply {
                    connectTimeout = 10_000
                    readTimeout = 10_000
                }
                try {
                    if (conn.responseCode != 200) return@launch
                    val raw = conn.inputStream.bufferedReader().use { it.readText() }
                    val decoded: PlantData = json.decodeFromString(raw)  // validate before caching
                    if (decoded.version != SCHEMA_VERSION) return@launch
                    cacheFile(context).writeText(raw)
                    context.getSharedPreferences(PREFS, Context.MODE_PRIVATE).edit()
                        .putLong(KEY_APP_VERSION, appVersion(context)).apply()
                } finally {
                    conn.disconnect()
                }
            } catch (_: Exception) {
                // best-effort — the bundled/cached data already rendered.
            }
        }
    }

    private fun cacheFile(context: Context) = File(context.cacheDir, "catalog.json")

    private fun appVersion(context: Context): Long =
        context.packageManager.getPackageInfo(context.packageName, 0).let { info ->
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) info.longVersionCode
            else @Suppress("DEPRECATION") info.versionCode.toLong()
        }

    fun country(id: String): Country =
        data.countries.firstOrNull { it.id == id }
            ?: data.countries.first { it.id == data.defaultCountry }

    val availableCountries: List<Country>
        get() = data.countries.filter { it.plants.isNotEmpty() }

    fun findPlant(slug: String): Pair<Plant, Country>? {
        for (country in data.countries) {
            country.plants.firstOrNull { it.slug == slug }?.let { return it to country }
        }
        return null
    }
}
