import Foundation

// Mirrors shared/plants.json, generated by scripts/export-native-data.cjs.
// Regenerate after any edit to src/data/* — never hand-edit the JSON.

enum Language: String, CaseIterable, Identifiable, Codable {
    // sah/ru/en are the trilingual base; mn/zh are added for the Mongolia
    // collection. Which subset a reader sees is decided per country.
    case sah, ru, en, mn, zh
    var id: String { rawValue }

    var label: String {
        switch self {
        case .sah: return "Саха"
        case .ru: return "Русский"
        case .en: return "English"
        case .mn: return "Монгол"
        case .zh: return "中文"
        }
    }

    /// Compact form for the segmented language picker, same as the web's
    /// LANGUAGES shortLabel.
    var shortLabel: String {
        switch self {
        case .sah: return "Саха"
        case .ru: return "Рус"
        case .en: return "Eng"
        case .mn: return "Мон"
        case .zh: return "中"
        }
    }
}

struct LocalizedText: Decodable, Hashable {
    let sah: String
    let ru: String
    let en: String
    let mn: String?
    let zh: String?

    // Requested language, or English as the universal fallback (mn/zh are
    // absent on Yakutia plants and never queried there).
    subscript(_ lang: Language) -> String {
        switch lang {
        case .sah: return sah
        case .ru: return ru
        case .en: return en
        case .mn: return mn ?? en
        case .zh: return zh ?? en
        }
    }
}

struct PlantNames: Decodable, Hashable {
    let sah: String
    let ru: String
    let en: String
    let latin: String
    let mn: String?
    let zh: String?

    subscript(_ lang: Language) -> String {
        switch lang {
        case .sah: return sah
        case .ru: return ru
        case .en: return en
        case .mn: return mn ?? en
        case .zh: return zh ?? en
        }
    }
}

struct Plant: Decodable, Identifiable, Hashable {
    let id: String
    let slug: String
    let imageId: String
    let hasIllustration: Bool
    let names: PlantNames
    let description: LocalizedText
    let medicinalUses: LocalizedText
    let habitat: LocalizedText
    let bloomingSeason: String
    let categories: [String]
    let color: String

    /// "Further reading": language-matched Wikipedia lookup, same query
    /// strategy as the web (sah name for sah wiki, Latin binomial elsewhere).
    /// Special:Search never 404s — it lands on the article or a same-language
    /// results page.
    func wikipediaURL(for lang: Language) -> URL? {
        // Always the reader's own Wikipedia subdomain. Native-language wikis
        // (Sakha/Mongolian/Chinese) resolve best from the plant's own name;
        // Russian/English from the Latin binomial.
        let query: String
        if lang == .sah || lang == .mn || lang == .zh {
            query = names[lang]
                .replacingOccurrences(of: #"\s*\([^)]*\)\s*"#, with: " ", options: .regularExpression)
                .trimmingCharacters(in: .whitespaces)
        } else {
            query = names.latin
        }
        var comps = URLComponents(string: "https://\(lang.rawValue).wikipedia.org/wiki/Special:Search")
        comps?.queryItems = [URLQueryItem(name: "search", value: query)]
        return comps?.url
    }

    static func == (lhs: Plant, rhs: Plant) -> Bool { lhs.slug == rhs.slug }
    func hash(into hasher: inout Hasher) { hasher.combine(slug) }
}

struct Country: Decodable, Identifiable {
    let id: String
    let imageBase: String
    /// Slug of the collection's cover plant (Sardaana for Yakutia, marigold for
    /// Mongolia). The cover of an encyclopedia is its finest plate.
    let heroSlug: String
    /// Languages this collection offers, in switcher order, plus its default.
    let languages: [Language]
    let defaultLanguage: Language
    let plants: [Plant]

    /// The cover plant, resolved from `heroSlug`; falls back to the last entry
    /// if the slug ever fails to match, so the hero is never nil.
    var heroPlant: Plant? {
        plants.first { $0.slug == heroSlug } ?? plants.last
    }
}

struct PlantData: Decodable {
    let version: Int
    let imageHost: String
    let defaultCountry: String
    let countries: [Country]
}

/// The plant dataset, loaded ONCE at startup from the best available source:
/// a catalog previously cached from the website (by this same app build), else
/// the snapshot bundled in the binary. The bundle is the authoritative baseline
/// so a fresh, fully-offline first launch always works; the cache is an
/// offline-first overlay. New content published to the site is fetched in the
/// background by `refresh()` and applied on the NEXT launch — the running
/// session is never mutated.
enum PlantStore {
    /// Schema version this build understands. A hosted catalog with a different
    /// `version` is refused — an older app must never decode a newer shape.
    static let schemaVersion = 1

    static let data: PlantData = loadCachedCatalog() ?? loadBundled()

    /// The snapshot compiled into the app bundle. A decode failure here is a
    /// build error, not a runtime condition — crash loudly.
    private static func loadBundled() -> PlantData {
        guard
            let url = Bundle.main.url(forResource: "plants", withExtension: "json"),
            let raw = try? Data(contentsOf: url),
            let decoded = try? JSONDecoder().decode(PlantData.self, from: raw)
        else {
            fatalError("Bundled plants.json missing or malformed — run scripts/export-native-data.cjs")
        }
        return decoded
    }

    /// A previously-fetched catalog is trusted only if it was cached by THIS app
    /// build (so a new binary's fresh bundle always wins after an update) and its
    /// schema matches. Any miss/decode failure → nil → fall back to bundled.
    private static func loadCachedCatalog() -> PlantData? {
        guard
            UserDefaults.standard.string(forKey: cacheBuildKey) == appBuild,
            let url = cacheURL,
            let raw = try? Data(contentsOf: url),
            let decoded = try? JSONDecoder().decode(PlantData.self, from: raw),
            decoded.version == schemaVersion
        else { return nil }
        return decoded
    }

    /// Best-effort over-the-air sync: fetch the hosted catalog and, if valid and
    /// schema-compatible, cache it for the next launch. Never touches the running
    /// session, never surfaces errors. Call once at app launch.
    static func refresh() {
        guard let catalogURL = URL(string: data.imageHost)?.appendingPathComponent("catalog.json") else { return }
        Task.detached(priority: .background) {
            guard
                let (raw, response) = try? await URLSession.shared.data(from: catalogURL),
                (response as? HTTPURLResponse)?.statusCode == 200,
                let decoded = try? JSONDecoder().decode(PlantData.self, from: raw),
                decoded.version == schemaVersion,
                let url = cacheURL
            else { return }
            try? raw.write(to: url, options: .atomic)
            UserDefaults.standard.set(appBuild, forKey: cacheBuildKey)
        }
    }

    private static let cacheBuildKey = "catalogCacheAppBuild"
    private static var appBuild: String {
        (Bundle.main.infoDictionary?["CFBundleVersion"] as? String) ?? "0"
    }
    private static var cacheURL: URL? {
        FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask)
            .first?.appendingPathComponent("catalog.json")
    }

    static func country(_ id: String) -> Country {
        data.countries.first { $0.id == id }
            ?? data.countries.first { $0.id == data.defaultCountry }
            ?? data.countries[0]
    }

    static var availableCountries: [Country] {
        data.countries.filter { !$0.plants.isEmpty }
    }

    static func findPlant(slug: String) -> (Plant, Country)? {
        for country in data.countries {
            if let plant = country.plants.first(where: { $0.slug == slug }) {
                return (plant, country)
            }
        }
        return nil
    }
}

/// Blooming-season sort, same order table as the web catalog:
/// earliest start first, unknown seasons last.
enum SeasonOrder {
    static let order = [
        "spring", "may-june", "may-july", "june-july",
        "june-august", "summer", "july-august", "autumn",
    ]

    static func rank(_ season: String) -> Int {
        order.firstIndex(of: season) ?? order.count
    }
}

/// Two-digit index numeral like the web's plate numbers: 0 → "01".
func plateNumeral(_ index: Int) -> String {
    String(format: "%02d", index + 1)
}
