import Foundation

// Mirrors shared/plants.json, generated by scripts/export-native-data.cjs.
// Regenerate after any edit to src/data/* — never hand-edit the JSON.

enum Language: String, CaseIterable, Identifiable {
    case sah, ru, en
    var id: String { rawValue }

    var label: String {
        switch self {
        case .sah: return "Саха"
        case .ru: return "Русский"
        case .en: return "English"
        }
    }

    /// Compact form for the segmented language picker, same as the web's
    /// LANGUAGES shortLabel.
    var shortLabel: String {
        switch self {
        case .sah: return "Саха"
        case .ru: return "Рус"
        case .en: return "Eng"
        }
    }
}

struct LocalizedText: Decodable, Hashable {
    let sah: String
    let ru: String
    let en: String

    subscript(_ lang: Language) -> String {
        switch lang {
        case .sah: return sah
        case .ru: return ru
        case .en: return en
        }
    }
}

struct PlantNames: Decodable, Hashable {
    let sah: String
    let ru: String
    let en: String
    let latin: String

    subscript(_ lang: Language) -> String {
        switch lang {
        case .sah: return sah
        case .ru: return ru
        case .en: return en
        }
    }
}

struct Plant: Decodable, Identifiable, Hashable {
    let id: String
    let slug: String
    let imageId: String
    let hasIllustration: Bool
    let names: PlantNames
    let description: LocalizedText
    let medicinalUses: LocalizedText
    let habitat: LocalizedText
    let bloomingSeason: String
    let categories: [String]
    let color: String

    /// "Further reading": language-matched Wikipedia lookup, same query
    /// strategy as the web (sah name for sah wiki, Latin binomial elsewhere).
    /// Special:Search never 404s — it lands on the article or a same-language
    /// results page.
    func wikipediaURL(for lang: Language) -> URL? {
        let query: String
        if lang == .sah {
            query = names.sah
                .replacingOccurrences(of: #"\s*\([^)]*\)\s*"#, with: " ", options: .regularExpression)
                .trimmingCharacters(in: .whitespaces)
        } else {
            query = names.latin
        }
        var comps = URLComponents(string: "https://\(lang.rawValue).wikipedia.org/wiki/Special:Search")
        comps?.queryItems = [URLQueryItem(name: "search", value: query)]
        return comps?.url
    }

    static func == (lhs: Plant, rhs: Plant) -> Bool { lhs.slug == rhs.slug }
    func hash(into hasher: inout Hasher) { hasher.combine(slug) }
}

struct Country: Decodable, Identifiable {
    let id: String
    let imageBase: String
    let plants: [Plant]
}

struct PlantData: Decodable {
    let version: Int
    let imageHost: String
    let defaultCountry: String
    let countries: [Country]
}

/// Loads the bundled dataset once. The JSON ships in the app bundle, so a
/// decode failure is a build error, not a runtime condition — crash loudly.
enum PlantStore {
    static let data: PlantData = {
        guard
            let url = Bundle.main.url(forResource: "plants", withExtension: "json"),
            let raw = try? Data(contentsOf: url),
            let decoded = try? JSONDecoder().decode(PlantData.self, from: raw)
        else {
            fatalError("Bundled plants.json missing or malformed — run scripts/export-native-data.cjs")
        }
        return decoded
    }()

    static func country(_ id: String) -> Country {
        data.countries.first { $0.id == id }
            ?? data.countries.first { $0.id == data.defaultCountry }
            ?? data.countries[0]
    }

    static var availableCountries: [Country] {
        data.countries.filter { !$0.plants.isEmpty }
    }

    static func findPlant(slug: String) -> (Plant, Country)? {
        for country in data.countries {
            if let plant = country.plants.first(where: { $0.slug == slug }) {
                return (plant, country)
            }
        }
        return nil
    }
}

/// Blooming-season sort, same order table as the web catalog:
/// earliest start first, unknown seasons last.
enum SeasonOrder {
    static let order = [
        "spring", "may-june", "may-july", "june-july",
        "june-august", "summer", "july-august", "autumn",
    ]

    static func rank(_ season: String) -> Int {
        order.firstIndex(of: season) ?? order.count
    }
}

/// Two-digit index numeral like the web's plate numbers: 0 → "01".
func plateNumeral(_ index: Int) -> String {
    String(format: "%02d", index + 1)
}
