/**
 * fetch-fonts.cjs — self-host the Google Fonts used by the app.
 *
 * Built to remove the third-party fonts.googleapis.com / fonts.gstatic.com
 * requests, which leaked every visitor's IP to Google and contradicted the
 * app's Privacy page ("no third-party tracking, no external network requests").
 *
 * Fetches the same family/weight spec index.html requested (with a modern
 * Chrome UA so Google returns woff2 + the full latin/cyrillic/cyrillic-ext
 * subsets Yakut needs), downloads every woff2 into public/fonts/, and writes
 * public/fonts/fonts.css with the @font-face rules rewritten to local paths.
 *
 * Re-runnable: node scripts/fetch-fonts.cjs
 */
const fs = require('fs');
const path = require('path');

const SPEC =
  'family=Inter:wght@300;400;500;600;700' +
  '&family=Playfair+Display:ital,wght@0,400;0,600;0,700;1,400' +
  '&family=PT+Serif:ital,wght@0,400;0,700;1,400;1,700' +
  '&display=swap';
const CSS_URL = `https://fonts.googleapis.com/css2?${SPEC}`;
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const OUT_DIR = path.join(__dirname, '../public/fonts');

async function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const cssRes = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
  if (!cssRes.ok) throw new Error(`CSS fetch failed: ${cssRes.status}`);
  let css = await cssRes.text();

  // Find every gstatic woff2 URL, download it, rewrite to a local path.
  const urls = [...new Set(css.match(/https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2/g) || [])];
  console.log(`Found ${urls.length} font files to download…`);

  let i = 0;
  for (const url of urls) {
    i++;
    const local = `font-${String(i).padStart(3, '0')}.woff2`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`font fetch failed ${res.status}: ${url}`);
    const buf = Buffer.from(await res.arrayBuffer());
    fs.writeFileSync(path.join(OUT_DIR, local), buf);
    // Rewrite ALL occurrences of this url in the CSS to the local path.
    css = css.split(url).join(`/fonts/${local}`);
    process.stdout.write(`  ✓ ${local} (${(buf.length / 1024).toFixed(0)}kb)\n`);
  }

  const banner =
    '/* Self-hosted Google Fonts (Inter, Playfair Display, PT Serif).\n' +
    '   Generated by scripts/fetch-fonts.cjs — do not edit by hand.\n' +
    '   Removes the third-party fonts.googleapis.com/gstatic.com requests. */\n';
  fs.writeFileSync(path.join(OUT_DIR, 'fonts.css'), banner + css);
  console.log(`\nWrote public/fonts/fonts.css (${urls.length} faces). Done.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
