// AUTO-GENERATED by scripts/gen-illustration-manifest.cjs — do not edit by hand.
// Botanical-plate slugs that have optimized image files in public/plants/.
// Regenerate with: node scripts/gen-illustration-manifest.cjs (or npm run optimize).
export const AVAILABLE_ILLUSTRATIONS: string[] = [
  "plant-01-ill",
  "plant-02-ill",
  "plant-03-ill",
  "plant-04-ill",
  "plant-05-ill",
  "plant-06-ill",
  "plant-07-ill",
  "plant-08-ill",
  "plant-09-ill",
  "plant-10-ill",
  "plant-11-ill",
  "plant-12-ill",
  "plant-13-ill",
  "plant-14-ill",
  "plant-15-ill",
  "plant-16-ill",
  "plant-17-ill",
  "plant-18-ill",
  "plant-19-ill",
  "plant-20-ill",
  "plant-21-ill",
  "plant-22-ill",
  "plant-23-ill"
];
